In [1]:
%load_ext lab_black

In [2]:
import json
import requests
import pandas as pd
from config import server_key

In [3]:
def extract_data(info):
    return {
        "Street Address": info["UnparsedAddress"],
        "Zip Code": info["PostalCode"],
        "List Price": info["ListPrice"],
        "Lat": info["Latitude"],
        "Long": info["Longitude"],
        "Tax Ammount": info["TaxAnnualAmount"],
        "School Dist": info["HighSchoolDistrict"],
        "List Date": info["ListingContractDate"],
    }

In [4]:
url = "https://api.bridgedataoutput.com/api/v2/OData/abor_ref/Property"
payload = {
    "access_token": server_key,
    "limit": 200,
}

In [20]:
# creates list to 5000 skiping by 200
count = 0
count_list = []
while count < 5000:
    count += 200
    count_list.append(count)

In [6]:
# Data for 2015

data_2015 = []
house_data = []
for e in count_list:
    pull_2015 = requests.get(
        f"https://api.bridgedataoutput.com/api/v2/OData/abor_ref/Properties?access_token={server_key}&$top=200&$skip={e}&$filter=year(ListingContractDate) eq 2015"
    ).json()
    data_2015.append(pull_2015)
    data_point = pull_2015["value"]
    for e in data_point:
        house_data.append(extract_data(e))

df_2015 = pd.DataFrame(house_data).drop_duplicates()

In [8]:
# Data for 2016

data_2016 = []
house_data = []
for e in count_list:
    pull_2016 = requests.get(
        f"https://api.bridgedataoutput.com/api/v2/OData/abor_ref/Properties?access_token={server_key}&$top=200&$skip={e}&$filter=year(ListingContractDate) eq 2016"
    ).json()
    data_2016.append(pull_2016)
    data_point = pull_2016["value"]
    for e in data_point:
        house_data.append(extract_data(e))

df_2016 = pd.DataFrame(house_data).drop_duplicates()

In [9]:
# Data for 2017

data_2017 = []
house_data = []
for e in count_list:
    pull_2017 = requests.get(
        f"https://api.bridgedataoutput.com/api/v2/OData/abor_ref/Properties?access_token={server_key}&$top=200&$skip={e}&$filter=year(ListingContractDate) eq 2017"
    ).json()
    data_2017.append(pull_2017)
    data_point = pull_2017["value"]
    for e in data_point:
        house_data.append(extract_data(e))

df_2017 = pd.DataFrame(house_data).drop_duplicates()

In [10]:
# Data for 2018

data_2018 = []
house_data = []
for e in count_list:
    pull_2018 = requests.get(
        f"https://api.bridgedataoutput.com/api/v2/OData/abor_ref/Properties?access_token={server_key}&$top=200&$skip={e}&$filter=year(ListingContractDate) eq 2018"
    ).json()
    data_2018.append(pull_2018)
    data_point = pull_2018["value"]
    for e in data_point:
        house_data.append(extract_data(e))

df_2018 = pd.DataFrame(house_data).drop_duplicates()

In [11]:
# Data for 2019

data_2019 = []
house_data = []
for e in count_list:
    pull_2019 = requests.get(
        f"https://api.bridgedataoutput.com/api/v2/OData/abor_ref/Properties?access_token={server_key}&$top=200&$skip={e}&$filter=year(ListingContractDate) eq 2019"
    ).json()
    data_2019.append(pull_2019)
    data_point = pull_2019["value"]
    for e in data_point:
        house_data.append(extract_data(e))

df_2019 = pd.DataFrame(house_data).drop_duplicates()

In [12]:
df_2015

,Street Address,Zip Code,List Price,Lat,Long,Tax Ammount,School Dist,List Date
0,"2228 S Lamar BLVD, Austin TX 78704",78704,2000000,30.247823,-97.773260,13712.00,None,2015-01-29
1,"913 E 12th ST, Austin TX 78702",78702,500000,30.271967,-97.729721,3570.00,None,2015-03-01
2,"3821 Juniper TRCE # 207, Austin TX 78738",78738,400000,30.307804,-97.933612,6038.00,None,2015-06-27
3,"1008 Main ST, Bastrop TX 78602",78602,300000,30.110873,-97.320438,6008.00,None,2015-07-17
4,"10880 E Crystal Falls PKWY, Leander TX 78641",78641,2000000,30.566044,-97.814137,5.00,None,2015-07-28
...,...,...,...,...,...,...,...,...
4995,"1405 Lorraine LOOP # 1405, Austin TX 78758",78758,200000,30.381466,-97.703017,4568.00,Austin ISD,2015-06-27
4996,"7314 Halbert DR, Austin TX 78750",78750,400000,30.377252,-97.799483,10060.00,Austin ISD,2015-06-26
4997,"3919 Kynard, Other TX 75215",75215,50000,32.759222,-96.761575,850.00,Other,2015-06-25
4998,"173 Jolie CIR, Other TX 78015",78015,200000,29.757704,-98.701051,3606.89,Other,2015-06-25
4999,"510 Ladin LN, Lakeway TX 78734",78734,700000,30.368940,-97.966915,12677.00,Lake Travis ISD,2015-06-27

In [13]:
df_2016

,Street Address,Zip Code,List Price,Lat,Long,Tax Ammount,School Dist,List Date
0,"000 CR 414, Other TX 77836",77836,100000,30.360280,-96.586390,1531.05,Other,2016-03-17
1,"Tract 5 Werchan LN, Coupland TX 78615",78615,100000,30.422918,-97.416130,574.00,Elgin ISD,2016-04-29
2,"4428 W Fm 696, Lexington TX 78947",78947,300000,30.388415,-97.156365,2117.00,Lexington ISD,2016-07-22
3,"635 Ramms DR, Florence TX 76527",76527,200000,30.883451,-97.783819,2144.00,Florence ISD,2016-06-04
4,"000 Mulberry CV, Bastrop TX 78602",78602,200000,30.169817,-97.237879,815.00,Bastrop ISD,2016-04-21
...,...,...,...,...,...,...,...,...
4960,"2101 Town Centre DR # 1805, Round Rock TX 78664",78664,200000,30.493414,-97.653300,4463.00,Round Rock ISD,2016-07-14
4961,"1421 Sleepy Hollow LN, New Braunfels TX 78130",78130,400000,29.734053,-98.105833,2409.00,New Braunfels ISD,2016-03-29
4962,"220 Tempranillo WAY, Lakeway TX 78738",78738,900000,30.355610,-98.010986,0.00,Lake Travis ISD,2016-06-14
4963,"114 Perpetuation DR, Austin TX 78734",78734,400000,30.344470,-97.964037,9333.00,Lake Travis ISD,2016-08-26
4965,"4401 Topacio, Spicewood TX 78669",78669,500000,30.366042,-98.075378,0.00,Lake Travis ISD,2016-09-06

In [14]:
df_2017

,Street Address,Zip Code,List Price,Lat,Long,Tax Ammount,School Dist,List Date
0,"1001 Fm 3403, Lexington TX 78947",78947,100000,30.358711,-96.972794,1895.0,Lexington ISD,2017-12-05
1,"9110 Bluff Springs RD, Austin TX 78744",78744,400000,30.156510,-97.770436,2917.0,Austin ISD,2017-11-13
2,"2721 Citation DR, Del Valle TX 78617",78617,2000,30.208155,-97.519728,NaN,Del Valle ISD,2017-11-06
3,"2125 State Highway 71 HWY W # B, Cedar Creek T...",78612,1000,30.143650,-97.477948,NaN,Bastrop ISD,2017-11-14
4,"408 Farmer LN, Jarrell TX 76537",76537,1000,30.811762,-97.593603,NaN,Jarrell ISD,2017-11-14
...,...,...,...,...,...,...,...,...
4995,"820 Anahuac DR, Leander TX 78641",78641,400000,30.573028,-97.834013,11256.0,Leander ISD,2017-08-30
4996,"6404 Siltstone LOOP, Killeen TX 76542",76542,200000,31.051715,-97.679425,5467.0,Killeen ISD,2017-09-01
4997,"8015 Arbia CV, Round Rock TX 78665",78665,300000,30.550802,-97.598780,10412.0,Hutto ISD,2017-07-24
4998,"200 Grosseto LN, Georgetown TX 78628",78628,400000,30.628319,-97.819751,10855.0,Liberty Hill ISD,2017-07-26
4999,"4301 Hookbilled Kite DR, Austin TX 78738",78738,500000,30.319724,-97.973970,10548.0,Lake Travis ISD,2017-07-26

In [15]:
df_2018

,Street Address,Zip Code,List Price,Lat,Long,Tax Ammount,School Dist,List Date
0,"11900 FM 2325, Wimberley TX 78676",78676,1000000,30.101981,-98.253937,13637.0,Blanco ISD,2018-01-30
1,"16308 Double Eagle DR, Austin TX 78717",78717,400000,30.506214,-97.756945,10274.0,Round Rock ISD,2018-07-27
2,"10300 Maydelle DR, Austin TX 78748",78748,300000,30.165736,-97.823884,5357.0,Austin ISD,2018-08-26
3,"5806 Circulo DR # 16, Lago Vista TX 78645",78645,100000,30.456308,-97.993109,2616.0,Lago Vista ISD,2018-04-06
4,"5100 Lea CV, Austin TX 78731",78731,700000,30.372487,-97.773488,11550.0,Austin ISD,2018-06-24
...,...,...,...,...,...,...,...,...
4993,"2105 Christoff LOOP, Austin TX 78748",78748,300000,30.145185,-97.844132,5763.0,Austin ISD,2018-05-12
4994,"1206 Van Horn WAY, Cedar Park TX 78613",78613,400000,30.485547,-97.847140,7288.0,Leander ISD,2018-04-30
4996,"1008 Placid Creek CT, Round Rock TX 78665",78665,300000,30.570695,-97.676481,8368.0,Round Rock ISD,2018-05-01
4998,"1016 Savanna LN, Cedar Park TX 78613",78613,300000,30.506153,-97.803863,7919.0,Leander ISD,2018-05-03
4999,"3710 Gentle Winds LN, Round Rock TX 78681",78681,300000,30.556274,-97.742045,7317.0,Round Rock ISD,2018-05-02

In [16]:
df_2019

,Street Address,Zip Code,List Price,Lat,Long,Tax Ammount,School Dist,List Date
0,"14407 Sandifer ST, Austin TX 78725",78725,200000,30.236913,-97.588632,3254.0,Del Valle ISD,2019-03-16
1,"209 Diamond Point DR, Dripping Springs TX 78620",78620,300000,30.195191,-98.084240,6677.0,Dripping Springs ISD,2019-04-01
2,"2315 Howry DR, Georgetown TX 78626",78626,200000,30.628371,-97.653496,4625.0,Georgetown ISD,2019-03-23
3,"107 Birdie DR, The Hills TX 78738",78738,400000,30.353846,-97.987496,4990.0,Lake Travis ISD,2019-03-29
4,"3801 Manchaca RD # 23, Austin TX 78704",78704,300000,30.235677,-97.784198,5195.0,Austin ISD,2019-04-04
...,...,...,...,...,...,...,...,...
4995,"240 Silver Maple DR, Kyle TX 78640",78640,200000,29.991171,-97.891943,6048.0,Hays ISD,2019-07-13
4996,"6716 Estana LN, Austin TX 78739",78739,500000,30.180822,-97.906074,11094.0,Austin ISD,2019-07-25
4997,"2803 Monika LN, Taylor TX 76574",76574,200000,30.588809,-97.426483,4650.0,Taylor ISD,2019-07-13
4998,"700 Huntingdon PL, Austin TX 78745",78745,300000,30.195640,-97.790138,6427.0,Austin ISD,2019-07-25
4999,"1407 Holly ST # A, Austin TX 78702",78702,700000,30.255181,-97.731752,14581.0,Austin ISD,2019-08-08

In [19]:
df_2015.to_csv("Data/2015_house.csv", index=False)
df_2016.to_csv("Data/2016_house.csv", index=False)
df_2017.to_csv("Data/2017_house.csv", index=False)
df_2018.to_csv("Data/2018_house.csv", index=False)
df_2019.to_csv("Data/2019_house.csv", index=False)